-- Script de configuração do banco de dados para o sistema "Meu Evento dos Sonhos"
-- Execute este script no editor SQL do Supabase

-- Criar tabela de eventos
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    drive_folder_id TEXT NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar tabela de uploads
CREATE TABLE IF NOT EXISTS uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    original_name TEXT,
    stored_name TEXT,
    guest_name TEXT,
    drive_file_id TEXT,
    drive_link TEXT,
    mime_type TEXT,
    size_bytes BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_events_active ON events(active);
CREATE INDEX IF NOT EXISTS idx_uploads_event_id ON uploads(event_id);
CREATE INDEX IF NOT EXISTS idx_uploads_guest_name ON uploads(guest_name);
CREATE INDEX IF NOT EXISTS idx_uploads_created_at ON uploads(created_at);

-- Criar políticas de segurança RLS (Row Level Security)
-- Nota: Ajuste conforme suas necessidades de segurança

-- Habilitar RLS nas tabelas
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;

-- Política para permitir leitura de eventos ativos (público)
CREATE POLICY "Allow read active events" ON events
    FOR SELECT USING (active = true);

-- Política para permitir inserção de uploads (público)
CREATE POLICY "Allow insert uploads" ON uploads
    FOR INSERT WITH CHECK (true);

-- Política para permitir leitura de uploads (público)
CREATE POLICY "Allow read uploads" ON uploads
    FOR SELECT USING (true);

-- Comentários para documentação
COMMENT ON TABLE events IS 'Tabela para armazenar informações dos eventos';
COMMENT ON TABLE uploads IS 'Tabela para armazenar metadados dos arquivos enviados';

COMMENT ON COLUMN events.name IS 'Nome do evento';
COMMENT ON COLUMN events.drive_folder_id IS 'ID da pasta no Google Drive';
COMMENT ON COLUMN events.active IS 'Indica se o evento está ativo para receber uploads';

COMMENT ON COLUMN uploads.event_id IS 'Referência ao evento';
COMMENT ON COLUMN uploads.original_name IS 'Nome original do arquivo';
COMMENT ON COLUMN uploads.stored_name IS 'Nome do arquivo armazenado no Drive';
COMMENT ON COLUMN uploads.guest_name IS 'Nome do convidado que enviou o arquivo';
COMMENT ON COLUMN uploads.drive_file_id IS 'ID do arquivo no Google Drive';
COMMENT ON COLUMN uploads.drive_link IS 'Link público para visualização do arquivo';
COMMENT ON COLUMN uploads.mime_type IS 'Tipo MIME do arquivo';
COMMENT ON COLUMN uploads.size_bytes IS 'Tamanho do arquivo em bytes';
